FROM adoptopenjdk/openjdk11
VOLUME application_account

ENV APPDIR=/opt/app/
WORKDIR ${APPDIR}

ARG JAR_FILE=../../build/libs/*.jar
COPY ${JAR_FILE} app.jar
ENTRYPOINT ["java","-jar","app.jar"]

#FROM adoptopenjdk/openjdk11ls /
#
##WORKDIR /app
#
#COPY gradlew .
#COPY gradle gradle
#COPY build.grade .
#COPY setting.grade .
#COPY src src
#COPY build/libs/*.jar app.jar
#
#RUN chmod +x ./gradlew  # gradlew 실행권한 부여
#RUN ./gradlew bootJar
#
#FROM adoptopenjdk/openjdk11
##build 이미지에서 build/libs/*.jar 파일을 app.jar로 복사
#COPY --from=builder build/libs/*.jar app.jar
#
#EXPOSE 8080
#ENTRYPOINT ["java","-jar","app.jar"]
#VOLUME /tmp
#





#FROM adoptopenjdk/openjdk11
#
#WORKDIR /app
#
#COPY .gradle/ .gradle
#COPY build.gradle ./
#COPY build/libs/account-book-0.0.1-SNAPSHOT.jar app.jar
#
#ENTRYPOINT ["java","-jar","app.jar"]